---
title: "Penguins EDA"
format:
  html:
    code-fold: true
---

## *Penguin Size and Mass by Sex and Species*

```{r, message=False, warning=False}
library(dplyr)
library(ggplot2)
library(dbplyr)

con <- DBI::dbConnect(
  duckdb::duckdb(), 
  dbdir = "my-db.duckdb"
  )
df <- dplyr::tbl(con, "penguins")
```

```{r}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
        ends_with("mm") | ends_with("g"),
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  dplyr::collect() %>%
  knitr::kable()
```

## *Penguin Size vs Mass by Species*

```{r, message=False, warning=False}
df %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")
```



## *Distribution of Bill Length by Species and Sex*
```{r, message=false, warning=False}
df %>%
  ggplot(aes(x = bill_length_mm, fill = species)) +
  geom_histogram(bins = 30, alpha = 0.6) +
  facet_wrap(~species + sex, scales = "free") +
  theme_minimal() +
  labs(title = "Distribution of Bill Length by Species and Sex")

```

## *Distributions Using Boxplots*
```{r, warning=False, message = False}
df %>%
  ggplot(aes(x = species, y = bill_length_mm, fill = species)) +
  geom_boxplot() +
  facet_wrap(~sex) +
  labs(y = "Bill Length (mm)", title = "Bill Length Distribution by Species and Sex")

```



```{r, message=False, warning=False}
DBI::dbDisconnect(con)
```
